// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LineChart: typeof import('./components/Echarts/LineChart.vue')['default']
    PanThumb: typeof import('./components/PanThumb/index.vue')['default']
    PieChart: typeof import('./components/Echarts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/Upload/index.vue')['default']
    UploadExcel: typeof import('./components/UploadExcel/index.vue')['default']
  }
}

export {}
